use serde::{Deserialize, Serialize};

/// Minimal reply content generated by the agent.
#[derive(Default, Clone, Debug, Serialize, Deserialize)]
pub struct OutboundPayload {
    pub text: Option<String>,
    pub media_urls: Vec<String>,
    pub interactive: Option<serde_json::Value>,
    pub reply_to_id: Option<String>,
    pub reply_to_tag: bool,
    pub reply_to_current: bool,
    pub audio_as_voice: bool,
    pub is_error: bool,
    pub is_reasoning: bool,
    pub channel_data: Option<serde_json::Value>,
}

/// Result of a successful outbound delivery.
#[allow(dead_code)]
#[derive(Default, Clone, Debug, Serialize, Deserialize)]
pub struct OutboundDeliveryResult {
    pub message_id: Option<String>,
    pub chat_id: Option<String>,
    pub timestamp: Option<u64>,
    pub meta: Option<serde_json::Value>,
}
