use std::io::{self, Write};
use std::path::Path;

use colored::Colorize;

struct ProviderInfo {
    name: &'static str,
    display: &'static str,
    api_key_env: &'static str,
    models: &'static [(&'static str, &'static str)], // (model_id, label)
    base_url: Option<&'static str>,
}

const PROVIDERS: &[ProviderInfo] = &[
    ProviderInfo {
        name: "openai",
        display: "OpenAI",
        api_key_env: "OPENAI_API_KEY",
        models: &[
            ("gpt-4o", "gpt-4o (recommended)"),
            ("gpt-4o-mini", "gpt-4o-mini (fast & cheap)"),
            ("o1", "o1 (reasoning)"),
            ("o3-mini", "o3-mini (reasoning, fast)"),
        ],
        base_url: None,
    },
    ProviderInfo {
        name: "anthropic",
        display: "Anthropic",
        api_key_env: "ANTHROPIC_API_KEY",
        models: &[
            ("claude-sonnet-4-20250514", "Claude Sonnet 4 (recommended)"),
            ("claude-haiku-4-5-20251001", "Claude Haiku 4.5 (fast)"),
            ("claude-opus-4-20250514", "Claude Opus 4 (powerful)"),
        ],
        base_url: None,
    },
    ProviderInfo {
        name: "gemini",
        display: "Google Gemini",
        api_key_env: "GEMINI_API_KEY",
        models: &[
            ("gemini-2.0-flash", "Gemini 2.0 Flash (recommended)"),
            ("gemini-2.0-pro", "Gemini 2.0 Pro"),
        ],
        base_url: None,
    },
    ProviderInfo {
        name: "ollama",
        display: "Ollama (local)",
        api_key_env: "OLLAMA_API_KEY",
        models: &[
            ("llama3.3", "Llama 3.3 (recommended)"),
            ("qwen2.5-coder:32b", "Qwen 2.5 Coder 32B"),
            ("deepseek-r1:32b", "DeepSeek R1 32B"),
        ],
        base_url: Some("http://localhost:11434/v1"),
    },
];

/// Run the interactive init wizard.
pub async fn run_init() -> Result<(), Box<dyn std::error::Error>> {
    println!();
    println!("{}", "═══ Synapse Setup Wizard ═══".bold().cyan());
    println!();

    // Check if config already exists
    let config_path = Path::new("synapse.toml");
    if config_path.exists() {
        println!("{} synapse.toml already exists.", "note:".yellow().bold());
        if !confirm("Overwrite existing config?")? {
            println!("{}", "Aborted.".dimmed());
            return Ok(());
        }
        println!();
    }

    // 1. Select provider
    println!("{}", "Select a provider:".bold());
    for (i, p) in PROVIDERS.iter().enumerate() {
        println!("  {}) {}", (i + 1).to_string().cyan(), p.display);
    }
    println!(
        "  {}) Custom (OpenAI-compatible)",
        (PROVIDERS.len() + 1).to_string().cyan()
    );

    let provider_idx = read_choice(1, PROVIDERS.len() + 1)?;
    println!();

    if provider_idx > PROVIDERS.len() {
        // Custom provider
        return run_custom_provider_init().await;
    }

    let provider = &PROVIDERS[provider_idx - 1];

    // 2. Select model
    println!("{}", "Select a model:".bold());
    for (i, (_, label)) in provider.models.iter().enumerate() {
        println!("  {}) {}", (i + 1).to_string().cyan(), label);
    }
    let model_idx = read_choice(1, provider.models.len())?;
    let (model_id, _) = provider.models[model_idx - 1];
    println!();

    // 3. API key env var
    let api_key_env = if provider.name == "ollama" {
        // Ollama doesn't need an API key
        println!(
            "{} Ollama runs locally — no API key needed.",
            "note:".blue().bold()
        );
        "OLLAMA_API_KEY".to_string()
    } else {
        println!(
            "API key environment variable [{}]:",
            provider.api_key_env.cyan()
        );
        let custom = read_line_default(provider.api_key_env)?;
        println!();

        // Check if the env var is set
        if std::env::var(&custom).is_err() {
            println!(
                "{} {} is not set. Set it before running synapse.",
                "warning:".yellow().bold(),
                custom.cyan()
            );
        } else {
            println!("{} {} is set", "ok:".green().bold(), custom.cyan());
        }
        custom
    };
    println!();

    // 4. Generate config
    let mut config = format!(
        r#"# Synapse Configuration (generated by synapse init)

[model]
provider = "{provider}"
model = "{model}"
api_key_env = "{api_key_env}"
"#,
        provider = provider.name,
        model = model_id,
        api_key_env = api_key_env,
    );

    if let Some(base_url) = provider.base_url {
        config.push_str(&format!("base_url = \"{}\"\n", base_url));
    }

    config.push_str(
        r#"
[agent]
system_prompt = "You are Synapse, a helpful AI assistant powered by the Synaptic framework. You can read and write files, execute commands, and help with complex coding tasks."
max_turns = 50

[agent.tools]
filesystem = true

[paths]
sessions_dir = ".sessions"
memory_file = "AGENTS.md"
"#,
    );

    // 5. Write config
    std::fs::write(config_path, &config)?;
    println!(
        "{} Config written to {}",
        "done:".green().bold(),
        "synapse.toml".cyan()
    );
    println!();

    // 6. Quick tips
    println!("{}", "Quick start:".bold());
    println!("  {}    — Interactive chat", "synapse".cyan());
    println!(
        "  {} — Run a coding task",
        "synapse task \"fix the bug\"".cyan()
    );
    println!("  {}   — Check setup health", "synapse doctor".cyan());
    println!();

    Ok(())
}

async fn run_custom_provider_init() -> Result<(), Box<dyn std::error::Error>> {
    println!("{}", "Custom OpenAI-compatible provider setup:".bold());
    println!();

    print!("  Base URL: ");
    io::stdout().flush()?;
    let base_url = read_line()?;

    print!("  Model name: ");
    io::stdout().flush()?;
    let model = read_line()?;

    print!("  API key env var [OPENAI_API_KEY]: ");
    io::stdout().flush()?;
    let api_key_env = read_line_default("OPENAI_API_KEY")?;
    println!();

    let config = format!(
        r#"# Synapse Configuration (generated by synapse init)

[model]
provider = "openai"
model = "{model}"
api_key_env = "{api_key_env}"
base_url = "{base_url}"

[agent]
system_prompt = "You are Synapse, a helpful AI assistant powered by the Synaptic framework. You can read and write files, execute commands, and help with complex coding tasks."
max_turns = 50

[agent.tools]
filesystem = true

[paths]
sessions_dir = ".sessions"
memory_file = "AGENTS.md"
"#,
    );

    std::fs::write("synapse.toml", &config)?;
    println!(
        "{} Config written to {}",
        "done:".green().bold(),
        "synapse.toml".cyan()
    );

    Ok(())
}

fn read_line() -> Result<String, Box<dyn std::error::Error>> {
    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    Ok(input.trim().to_string())
}

fn read_line_default(default: &str) -> Result<String, Box<dyn std::error::Error>> {
    let input = read_line()?;
    if input.is_empty() {
        Ok(default.to_string())
    } else {
        Ok(input)
    }
}

fn read_choice(min: usize, max: usize) -> Result<usize, Box<dyn std::error::Error>> {
    loop {
        print!("{} ", ">".green().bold());
        io::stdout().flush()?;
        let input = read_line()?;
        if let Ok(n) = input.parse::<usize>() {
            if n >= min && n <= max {
                return Ok(n);
            }
        }
        eprintln!("Please enter a number between {} and {}", min, max);
    }
}

fn confirm(prompt: &str) -> Result<bool, Box<dyn std::error::Error>> {
    print!("{} [y/N] ", prompt);
    io::stdout().flush()?;
    let input = read_line()?;
    Ok(matches!(input.to_lowercase().as_str(), "y" | "yes"))
}
